version: '3.8'

services:
  traefik:
    image: traefik:v2.11
    command:
      - --api.insecure=false
      - --providers.docker=true
      - --providers.file.directory=/etc/traefik
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Optional: Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml
      - ./traefik/acme.json:/etc/traefik/acme.json
    networks:
      - proxy

networks:
  proxy:
    external: true
