services:
  app:
    depends_on:
      postgres:
        condition: service_healthy
    image: docuseal/docuseal:latest
    volumes:
      - ./docuseal:/data/docuseal
    environment:
      - FORCE_SSL=true
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/docuseal
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.docuseal.rule=Host(`${HOST}`)
      - traefik.http.routers.docuseal.entrypoints=websecure
      - traefik.http.routers.docuseal.tls.certresolver=letsencrypt

  postgres:
    image: postgres:15
    volumes:
      - './pg_data:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: docuseal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - proxy

networks:
  proxy:
    external: true
